apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: precious-certificate
  namespace: sock-shop
spec:
  secretName: precious-secret
  issuerRef: 
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: precious.me
  dnsNames:
  - precious.me
 